MyPortfolioAspNetMvc5/Controllers/UILayoutController.cs
using MyPortfolioAspNetMvc5.Repositoryies;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyPortfolioAspNetMvc5.Controllers
{
    [AllowAnonymous]
    public class UILayoutController : Controller
    {
        AboutRepository _aboutRepository = new AboutRepository();
        public ActionResult Index()
        {
           
            return View();
        }

        public PartialViewResult UIHeaderPartial()
        {

            return PartialView();
        }

        public PartialViewResult UINavbarPartial()
        {
            var value = _aboutRepository.GetList();
          
            return PartialView(value);
        }

        public PartialViewResult UIScriptsPartial()
        {

            return PartialView();
        }
    }
}

MyPortfolioAspNetMvc5/Views/UILayout/Index.cshtml
@model List<MyPortfolioAspNetMvc5.Models.Entity.Abouts>
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="tr">
@Html.Partial("~/Views/UILayout/UIHeaderPartial.cshtml")
<body id="page-top">
    @Html.Action("UINavbarPartial", "UILayout")

    <div class="container-fluid p-0">
        @RenderBody()
    </div>
    @Html.Partial("~/Views/UILayout/UIScriptsPartial.cshtml")
</body>
</html>

MyPortfolioAspNetMvc5/Views/UILayout/UIHeaderPartial.cshtml
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewBag.Title</title>
    <link rel="icon" type="image/x-icon" href="~/Templates/startbootstrap-resume-gh-pages/assets/img/favicon.ico" />
    <script src="https://use.fontawesome.com/releases/v5.15.1/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:500,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Muli:400,400i,800,800i" rel="stylesheet" type="text/css" />
    <link href="~/Templates/startbootstrap-resume-gh-pages/css/styles.css" rel="stylesheet" />
</head>

MyPortfolioAspNetMvc5/Views/UILayout/UINavbarPartial.cshtml
@model List<MyPortfolioAspNetMvc5.Models.Entity.Abouts>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top" style="background-color: #bd5d38 !important" id="sideNav">
    <a class="navbar-brand js-scroll-trigger" href="#page-top">
        <span class="d-block d-lg-none">Sinan Tosun</span>
        @foreach (var item in Model)
        {
            <span class="d-none d-lg-block"><img class="img-fluid img-profile rounded-circle mx-auto mb-2" src="@item.ImageURL" alt="" /></span>
        }



    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav">
            <li class="nav-item"><a class="nav-link js-scroll-trigger" href="/Default/Index#about">Hakkımda</a></li>
            <li class="nav-item"><a class="nav-link js-scroll-trigger" href="/Default/Index#projects">Projelerim</a></li>
            <li class="nav-item"><a class="nav-link js-scroll-trigger" href="/Default/Index#experience">Deneyimlerim</a></li>
            <li class="nav-item"><a class="nav-link js-scroll-trigger" href="/Default/Index#education">Eğitim Hayatım</a></li>
            <li class="nav-item"><a class="nav-link js-scroll-trigger" href="/Default/Index#skills">Yeteneklerim</a></li>
            <li class="nav-item"><a class="nav-link js-scroll-trigger" href="/Default/Index#interests">Hobilerim</a></li>
            <li class="nav-item"><a class="nav-link js-scroll-trigger" href="/Default/Index#awards">Sertifikalarım</a></li>
            <li class="nav-item"><a class="nav-link js-scroll-trigger" href="/Default/Index#contact">İletişim</a></li>
        </ul>
    </div>
</nav>

MyPortfolioAspNetMvc5/Views/UILayout/UIScriptsPartial.cshtml
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
<script src="~/Templates/startbootstrap-resume-gh-pages/js/scripts.js"></script>