MyPortfolioAspNetMvc5/Controllers/AdminLayoutController.cs
using MyPortfolioAspNetMvc5.DAL;
using MyPortfolioAspNetMvc5.Models.Entity;
using MyPortfolioAspNetMvc5.Repositoryies;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyPortfolioAspNetMvc5.Controllers
{
    [SessionTimeOut]
    public class AdminLayoutController : Controller
    {

        public ActionResult Index()
        {

            return View();
        }
        AboutRepository aboutRepository = new AboutRepository();
        public PartialViewResult Invoke()
        {

            var value = aboutRepository.GetList().First();
            ViewBag.NameSurname = value.Name + " " + value.Surname;
            ViewBag.ImageURL = value.ImageURL;
            return PartialView();
        }
    }
}

MyPortfolioAspNetMvc5/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
@Html.Partial("~/Views/LayoutPartial/AdminLayoutPartials/AdminLayoutHeaderPartial.cshtml")
<body class="hold-transition sidebar-mini">

    <div class="wrapper">

        <nav class="main-header navbar navbar-expand navbar-white navbar-light">

            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
            </ul>

        </nav>

        <aside class="main-sidebar sidebar-dark-primary elevation-4">

            <a href="#" class="brand-link">
                <img src="~/Templates/AdminLTE-3.0.4/dist/img/AdminLTELogo.png"
                     alt="AdminLTE Logo"
                     class="brand-image img-circle elevation-3"
                     style="opacity: .8">
                <span class="brand-text font-weight-light">CV Admin Paneli</span>
            </a>


            <div class="sidebar">

                @Html.Action("Invoke", "AdminLayout")
                

                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <li class="nav-item">
                            <a href="/Projects/Index" class="nav-link">
                                <i class="nav-icon fas fa-star"></i>
                                <p>
                                    Projelerim
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="/Projects/AddProjectImage/" class="nav-link">
                                <i class="nav-icon fas fa-upload"></i>
                                <p>
                                    Proje Görseli Ekle
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="/Category/Index" class="nav-link">
                                <i class="nav-icon fas fa-chart-area"></i>
                                <p>
                                    Kategoriler
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="/Abouts/Index" class="nav-link">
                                <i class="nav-icon fas fa-user"></i>
                                <p>
                                    Hakkımda
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="/Education/Index" class="nav-link">
                                <i class="nav-icon fas fa-book"></i>
                                <p>
                                    Eğitimlerim
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="/Experince/Index" class="nav-link">
                                <i class="nav-icon fas fa-history"></i>
                                <p>
                                    Deneyimlerim
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="/Interests/Index" class="nav-link">
                                <i class="nav-icon fas fa-apple-alt"></i>
                                <p>
                                    Hobilerim
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="/Skills/Index" class="nav-link">
                                <i class="nav-icon fas fa-skiing"></i>
                                <p>
                                    Yeteneklerim
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="/Certificate/Index" class="nav-link">
                                <i class="nav-icon fas fa-certificate"></i>
                                <p>
                                    Sertifikalarım
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="/Contact/Index" class="nav-link">
                                <i class="nav-icon fas fa-mail-bulk"></i>
                                <p>
                                    Mesajlar
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="/SocialMedia/Index" class="nav-link">
                                <i class="nav-icon fas fa-users"></i>
                                <p>
                                    Sosyal Medya
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="/ProfileSettings/Index" class="nav-link">
                                <i class="nav-icon fas fa-lock"></i>
                                <p>
                                   Ayarlar
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="/Login/SignOut" class="nav-link">
                                <i class="nav-icon fas fa-sign-out-alt"></i>
                                <p>
                                    Çıkış Yap
                                </p>
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
        </aside>
        <div class="content-wrapper">

            <section class="content">

                <br />
                <div class="card">
                    @RenderBody()

                </div>
            </section>

        </div>


        <footer class="main-footer">

            <strong>Copyright &copy; @DateTime.Now.Year </strong> Tüm Haklar Saklıdır.
        </footer>



    </div>

    @Html.Partial("~/Views/LayoutPartial/AdminLayoutPartials/AdminLayoutScriptsPartial.cshtml")
</body>
</html>

MyPortfolioAspNetMvc5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>